{{- if and (.Values.matchfunction).enabled ((.Values.matchfunction).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas.matchfunction.serviceAccountName" . }}
  namespace: {{ include "atlas.matchmaking-namespace" . }}
  labels:
    {{- include "atlas.matchfunction.labels" . | nindent 4 }}
  {{- with .Values.matchfunction.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
