{{- if (.Values.matchfunction).enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlas.matchfunction.fullname" . }}
  namespace: {{ include "atlas.matchmaking-namespace" . }}
  labels:
    {{- include "atlas.matchfunction.labels" . | nindent 4 }}
spec:
  type: {{ .Values.matchfunction.service.type }}
  ports:
    - port: {{ .Values.matchfunction.service.port }}
      targetPort: {{ .Values.matchfunction.service.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "atlas.matchfunction.selectorLabels" . | nindent 4 }}
{{- end -}}
