{{- if (.Values.analytics).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "atlas.analytics.fullname" . }}
  labels:
    {{- include "atlas.analytics.labels" . | nindent 4 }}
data:
{{- if .Values.analytics.extraEnv }}
{{ toYaml .Values.analytics.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.analytics.config }}
  NODE_CONFIG: '{{ mustToJson .Values.analytics.config }}'
{{- end }}
{{- end -}}
