{{- if and (.Values.api).enabled ((.Values.api).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas.api.serviceAccountName" . }}
  labels:
    {{- include "atlas.api.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
