{{- if and (.Values.gameserver).enabled ((.Values.gameserver).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas.gameserver.serviceAccountName" . }}
  labels:
    {{- include "atlas.gameserver.labels" . | nindent 4 }}
    {{- with .Values.gameserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
