{{- if and (.Values.testbot).enabled ((.Values.testbot).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas.testbot.serviceAccountName" . }}
  labels:
    {{- include "atlas.testbot.labels" . | nindent 4 }}
  {{- with .Values.testbot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
