{{- if (.Values.testbot).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "atlas.testbot.fullname" . }}
  labels:
    {{- include "atlas.testbot.labels" . | nindent 4 }}
data:
{{- if .Values.testbot.extraEnv }}
{{ toYaml .Values.testbot.extraEnv | indent 2 }}
{{- end }}
{{- end }}
