# Default values for atlas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: atlas.dev

bot:
  enabled: true
  name: bot

  replicaCount: 1
  image:
    repository: lagunalabs/atlas-bot
    tag: latest
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 3030

  serviceAccount:
    create: true
    annotations: {}
    name: