# Default values for atlas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: atlas.dev

builder:
  enabled: true
  name: atlas-builder

  replicaCount: 1
  image:
    repository: lagunalabs/atlas-builder
    tag: latest
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 3030

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.social.local
        paths: ["/"]
    # tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


  serviceAccount:
    create: true
    annotations: {}
    name:

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}

  # Extra Environment variables to configure xrsocial
  extraEnv:

sql:
  database: atlas
  user: server
  password: password
  host: ""
  port: 3306