apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rippled.fullname" . }}
  labels:
    {{- include "rippled.labels" . | nindent 4 }}
data:
  rippled.cfg: |-
{{ .Files.Get "config/rippled.cfg" | indent 4 }}
  validators.txt: |-
{{ .Files.Get "config/validators.txt" | indent 4 }}
